version: '2'
services:
  suitecrm:
    image: 'jenkins/jenkins:2.204.1'
    container_name: 'jenkins_server'
    ports:
      - '9080:8080'
      - '5000:5000'
    volumes:
      - '${JENKINS_VOLUME}:/var/jenkins_home'
volumes:
  home:
    driver: local