version: '3.6'

services:
  orangehrm:
    image: 'bitnami/orangehrm:4.3.4-0-debian-10-r22'
    container_name: bitnami_orangehrm
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - ORANGEHRM_DATABASE_NAME=orangehrm_db
      - ORANGEHRM_DATABASE_USER=db_user
      - ORANGEHRM_DATABASE_PASSWORD=db_password
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=orangehrm_db
      - MYSQL_CLIENT_CREATE_DATABASE_USER=db_user
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=db_password
      - MARIADB_ROOT_PASSWORD=db_root_password
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - '${ORANGEHRM_VOLUME}:/bitnami'
    depends_on:
      - mariadb
    networks:
      - hrm-net

  mariadb:
    image: 'bitnami/mariadb:10.2'
    container_name: bitnami_mariadb
    environment:
      - MARIADB_DATABASE=orangehrm_db
      - MARIADB_USER=db_user
      - MARIADB_PASSWORD=db_password
      - MARIADB_ROOT_PASSWORD=db_root_password
    ports:
      - '3306:3306'
    volumes:
      - '${ORANGEHRM_MADIADB_VOLUME}:/bitnami'
    networks:
      - hrm-net

volumes:
  orangehrm_mariadb_data:
    driver: local
  orangehrm_data:
    driver: local

networks:
  hrm-net:
    name: ${CLUSTER_NETWORK}
    driver: bridge