version: '3.6'

services:
  selenoid:
    image: "aerokube/selenoid:latest"
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${SELENOID_VOLUME}:/etc/selenoid:ro"
      - "${VIDEO_VOLUME}:/opt/selenoid/video"
      - "${LOGS_VOLUME}:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=${VIDEO_VOLUME}
    command: ["-conf", "/etc/selenoid/browsers.json",
              "-container-network", "${CLUSTER_NETWORK}",
              "-video-output-dir", "/opt/selenoid/video",
              "-log-output-dir", "/opt/selenoid/logs",
              "-service-startup-timeout", "${SERVICE_STARTUP_TIMEOUT}",
              "-session-delete-timeout", "${SESSION_DELETE_TIMEOUT}",
              "-timeout", "${TIMEOUT}",
              "-capture-driver-logs"]
    networks:
      - cluster

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    container_name: selenoid-ui
    ports:
      - "9090:8080"
    depends_on:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]
    networks:
      - cluster

networks:
  cluster:
    external:
      name: ${CLUSTER_NETWORK}