#version: '2'
#services:
#  mariadb:
#    image: 'bitnami/mariadb:10.3.21-debian-9-r17'
#    #image: 'bitnami/mariadb:10.3'
#    environment:
#      - MARIADB_DATABASE=bitnami_suitecrm
#      - MARIADB_USER=db_user
#      - MARIADB_PASSWORD=db_password
#      #- MARIADB_ROOT_USER=db_root_user
#      #`- MARIADB_ROOT_PASSWORD=db_root_password
#      - ALLOW_EMPTY_PASSWORD=yes
#    ports:
#      - '3306:3306'
#    volumes:
#      - './mariadb_data:/bitnami'
#    #entrypoint: ["sh", "-c", "sleep 20`73600"]
#
#  suitecrm:
#    image: 'bitnami/suitecrm:7.11.10-debian-9-r33'
#    #image: 'bitnami/suitecrm:7'
#    environment:
#      - MARIADB_HOST=mariadb
#      - MARIADB_PORT_NUMBER=3306
#      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
#      - SUITECRM_DATABASE_USER=db_user
#      - SUITECRM_DATABASE_PASSWORD=db_password
#      - SUITECRM_USERNAME=suitecrm_user
#      - SUITECRM_PASSWORD=suitecrm_password
#      - ALLOW_EMPTY_PASSWORD=yes
#    ports:
#      - '80:80'
#      - '443:443'
#    volumes:
#      - './suitecrm_data:/bitnami'
#    depends_on:
#      - mariadb
#volumes:
#  mariadb_data:
#    driver: local
#  suitecrm_data:
#    driver: local


version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_suitecrm
      - MARIADB_DATABASE=bitnami_suitecrm
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    volumes:
      - '${MARIADB_VOLUME}:/bitnami'
  suitecrm:
    image: 'bitnami/suitecrm:7'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - '${SUITECRM_VOLUME}:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local